##############################################################
##################         Site Info         #################
##############################################################

siteName: 'Kawaisou' # the name of your blog
# siteSubTitle: '河合庄' # subtitle of your blog, will show in the format of 'siteName - siteSubTitle', default to none
siteDescription: 'Place for my thoughts' # description of the blog
author: 'Kawai Ritsu' # the name of author
authorDescription: '趣味は読書です'
siteIcon: 'favicon.ico' # the path to site icon
createTime: '2017' # creation time of the site
avatar: 'avatar.jpg' # avatar of user
personalPage: 'https://github.com/H2O-2' # personal page of user

#Open Graph Data
og: !!map
  image: 'favicon.ico'
  title: 'Kawaisou'
  description: 'Place for my thoughts'



##############################################################
##################        Site Config        #################
##############################################################

theme: 'theme-notes' # theme to use for your site
rootURL: 'http://blog.h2o2.com/' # the root URL of your blog, i.e. URL without subdirectories
rootDir: '/' # this is the root directory of your blog. E.g. if the blog URL is blog.name.com, then the value should be '/'
pageDir: 'page' # directory for pagination
archiveDir: 'archive' # directory for archive page
postDir: 'post' # directory for your posts
timeFormat: 'MMM D, YYYY' # format of post time, see https://momentjs.com/docs/#/displaying/ for more formats.
preprocess: true # Using css preprocessors (sass/scss) or not, default to true



##############################################################
##################        Deployment         #################
##############################################################

repoURL: 'https://github.com/H2O-2/ritsu' # git repo you are shipping to
branch: 'master' # git branch you want to use
commitMsg: 'New post: ' # git commit message, defaut is 'New post: {{postName}}'
